apiVersion: v1
kind: Service
metadata:
  name: merge-sort
  namespace: default
  labels:
   app: merge-sort
   service: merge-sort
spec:
  selector:
    app: merge-sort
  type: NodePort
  ports:
    - protocol: TCP
      name: http
      port: 8080
      targetPort: 3000