---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: merge-sort
  namespace: default
  labels:    
    app: merge-sort
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: merge-sort
      version: v1
  template:
    metadata:
      labels:
        app: merge-sort
        version: v1
      annotations:
        sidecar.istio.io/extraStatTags: destination_port,request_host,request_path,request_url_path,request_method,request_headers,request_referer,request_useragent,request_query
    spec:
      containers:
        - name: merge-sort-app
          image: elliotmtz12/merge-sort:latest
          imagePullPolicy: Always
          env:
            - name: TZ
              value: America/Tijuana
          ports:
            - containerPort: 3000
              protocol: TCP
